name: "deploy"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: "ssh://dokku@45.55.45.5:22/awards"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          branch: main
          git_push_flags: --force
